"""empty message

Revision ID: 57a8b5110440
Revises: 1bf284d4fe63
Create Date: 2020-08-31 16:17:06.416082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a8b5110440'
down_revision = '1bf284d4fe63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('langueges', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languege',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('langueges_list', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_list', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('levels')
    op.drop_table('languege')
    op.drop_table('developers')
    # ### end Alembic commands ###
